### ISSUE TITLE
对多设备受多人控制的策略疑问

### ISSUE THREAD

**Issue by CollapsarLi** [lab798/cognito-with-iot-core#1]
Hi ：
    遇到一位中国的架构师(*^▽^*)，您好 最近我需要实现一个和您提出场景十分相似的需求。在查阅资料过程中在AWS官网上拜读您这篇文章。但这里对您文中的权限部分有疑问。您提出的场景是：
- 用户A只能发布消息到/userA/deviceX的topic中
- 多个设备可能受同时受多人控制，此时用户B和C都有权限发布消息到/device2/temp
文中策略
`  "Action": "iot:Publish",
      "Resource": "arn:aws:iot:<your-region-code>:<account-id>:topic/${cognito-identity.amazonaws.com:sub}/`
这样限制后可以做到 mobile 只能IdentityID 为开头发送消息实现了需求1。但文中策略配置好像并不能实现需求2？

**Comment by salander0411** [comment]
Hi @CollapsarLi ，多谢你的问题，你可以看到我的README里面有一个NoSQL table的截图，这个table维护了identityID和device list之间的关系。

在如你所说的需求2的场景中，希望实现多个设备被多人控制，此时只需要多个APP end user同时去绑定这个设备就可以了。现实场景可能是扫描产品说明书里面的QR Code等等，也欢迎你提出更多想法或者意见 : )

**Comment by CollapsarLi** [comment]
Hi @salander0411 感谢您的回复，我理解到您的意思了，多个APP对应地应该是 
`${cognito-identity.amazonaws.com:sub}/ThingName/temp`,
不同app 对应的indentityID是不同的。可以在IOT 规则通配出 +/ThingName/temp 然后republic 设备subscribe的消息。这样就实现了多个用户控制同一设备。

我实现需求的应用场景是多个用户可以操作同一个设备的shadow。
目前采用为设备创建一个Identity Pool身份池，用身份池产生的Identity id作为ThingName 创建对应iot thing 勉强解决这个问题。
`"Resource"：“arn:aws:iot:<your-region-code>:<account-id>::thing/${cognito-identity.amazonaws.com:sub}"`




`

**Comment by InfiniteYuan1** [comment]
@salander0411 可以加个qq吗，想咨询一些问题。十分感谢。460528348
